# Generated by Django 4.1 on 2022-10-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
