# Generated by Django 4.1 on 2022-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_resume_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='dob',
            field=models.DateField(),
        ),
    ]
