# Generated by Django 4.1 on 2022-10-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_resume_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='doc',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='docs/'),
        ),
    ]
